# Angulos de Euler rpy

- De ángulos rpy a matriz de rotación (problema directo)
- De matriz de rotación a ángulos rpy (problema inverso)

In [11]:
import numpy as np
from scipy.spatial.transform import Rotation as R

# Matriz de rotación (ejemplo)
R_mat = R.from_euler('xyz', [0.3, 0.5, 1.0]).as_matrix()
print("Matriz de rotación: \n",R_mat)

# A Euler (roll, pitch, yaw)
rpy = R.from_matrix(R_mat).as_euler('xyz')
print("RPY:", rpy)

# Volver a matriz
R_mat2 = R.from_euler('xyz', rpy).as_matrix()
print("Vuelvo a matriz de rotación: \n",R_mat2)

Matriz de rotación: 
 [[ 0.47415988 -0.72733794  0.496137  ]
 [ 0.73846026  0.63539006  0.22573416]
 [-0.47942554  0.25934338  0.83838664]]
RPY: [0.3 0.5 1. ]
Vuelvo a matriz de rotación: 
 [[ 0.47415988 -0.72733794  0.496137  ]
 [ 0.73846026  0.63539006  0.22573416]
 [-0.47942554  0.25934338  0.83838664]]


## Dos soluciones posibles

In [27]:
rpy1 = np.array([0.3, 2.0, 1.0])
R_mat = R.from_euler('xyz', rpy1).as_matrix()
print("Primera solución rpy =", rpy1)
print("Matriz de rotación R=\n",R_mat)

# otra representación válida
rpy2 = R.from_matrix(R_mat).as_euler('xyz')
R_mat2 = R.from_euler('xyz', rpy1).as_matrix()
print("Segunda solución rpy =", rpy2)
print("Matriz de rotación R=\n",R_mat2)


Primera solución rpy = [0.3 2.  1. ]
Matriz de rotación R=
 [[-0.2248451  -0.65870019  0.71802419]
 [-0.35017549  0.74228703  0.57130298]
 [-0.90929743 -0.1229798  -0.39756026]]
Segunda solución rpy = [-2.84159265  1.14159265 -2.14159265]
Matriz de rotación R=
 [[-0.2248451  -0.65870019  0.71802419]
 [-0.35017549  0.74228703  0.57130298]
 [-0.90929743 -0.1229798  -0.39756026]]


## Gimbal lock

In [29]:
# pitch = 90° → gimbal lock
# Ejemplo de slides
rpy_gl = np.array([0.0, -np.pi/2, np.pi/2])
R_mat = R.from_euler('xyz', rpy_gl)

# Intentar recuperar Euler
rpy_rec = R_mat.as_euler('xyz')

print("RPY original:", rpy_gl)
print("RPY recuperado:", rpy_rec)

# Tengo infinitas soluciones: en este ejemplo cualquier combinación r+y=pi/2


RPY original: [ 0.         -1.57079633  1.57079633]
RPY recuperado: [ 1.57079633 -1.57079633  0.        ]
